# Generated by Django 4.2.6 on 2023-10-09 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('categories', models.CharField(max_length=200)),
                ('date_de_publication', models.IntegerField(verbose_name=20)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='upload/images')),
            ],
        ),
    ]
