# Generated by Django 4.2.6 on 2023-10-09 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='date_de_publication',
        ),
        migrations.AddField(
            model_name='movie',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
